[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/resume"
  to = "/Shobhit-Sirohi-Resume-Front-End.pdf"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200